spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/munozy/demo-config

server:
  port: 8888
  servlet:
    context-path: /spring-cloud-config-server

